### PR TITLE
Edits to README.md

### LINKED ISSUE #143: Edits to README.md for Clarity
Make a few edits to README.md to improve clarity.

### PR DESCRIPTION
**Pull request by jwharrie**
Edited the "highly customizable and flexible..." bullet point of features section. Changed "...a node editor and custom scripting language, named Maxim" to "...a node editor and Maxim, a custom scripting language." The edit clarifies that it's only the custom scripting language that is called Maxim (if that is what you meant).

Edited presentation of instructions in building backend. The two separate instructions are in bullets and are each preceded by a bolded title . It is now clear to the reader that there are two options in building backends.

Fixes #143

### CODE REVIEW

**Comment by cpdt** [comment]
Hey, thanks for the PR!

Looks good to me, just a couple of things:

 - Do you think you could change the backend headings to use Markdown headings (e.g. `### bla`) instead of bold text? Just because it allows them to be used as an anchor.
 - The "VST2 Instrument" instructions are both for the VST instrument _and_ effect. I think it makes sense to keep these together, but do you think you could change the title to reflect that? The text in that section could do with some clarification to, if you're happy to.

**Comment by jwharrie** [comment]
Okay. I'll look into your suggestions.

**Comment by jwharrie** [comment]
I made edits based on your suggestions.

**Comment by cpdt** [comment]
Looks good, thanks!

**Pull request merged**
